name: Deploy to EC2

on:
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jar-file
        path: build/libs/*.jar

    - name: Deploy to EC2
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "build/libs/*.jar"
        target: "/home/ec2-user/your-app-name.jar"

    - name: Execute remote SSH command
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo systemctl stop your-app
          sudo systemctl start your-app
